version: '3.7'

networks:
  private:
  web:
    external:
      name: web
services: 
    
  mariadbprod:
   image: mariadb:10.9.3
   #build: $PWD/db/mariadb
   container_name: mariadbpreprod
   restart: always
   volumes:
    - /home/venichelle/workflow/data/dbpreprod:/var/lib/mysql
    - ./:/docker-entrypoint-initdb.d
  
   environment:
    MYSQL_DATABASE: thetiptop_preprod
    MYSQL_ROOT_PASSWORD: archi20
    MYSQL_USER: root
    MYSQL_PASSWORD: admin
   networks:
    - web
   ports:
    - 3307:3306
    
