version: '3.7'

networks:
  private:
  web:
    external:
      name: web
services: 

  api-prod:
   image: dsparchiweb020vm/api_prod 
   container_name: api-prod
   networks:
    - web
    - private
   ports:
    - 9191:9292
   labels:
     - 'traefik.enable=true'
     - 'traefik.http.routers.api-prod.rule=Host(`api.prod.dsp-archiweb020-vm.fr`)'
     - 'traefik.http.routers.api-prod.tls=true'
     - 'traefik.http.routers.api-prod.tls.certresolver=letsencrypt'
     - 'traefik.http.routers.api-prod.service=api-prod'
     - 'traefik.http.services.api-prod.loadbalancer.server.port=80'
     - 'traefik.http.routers.api-prod.entrypoints=websecure'
     - 'traefik.http.routers.api-prod.tls.certresolver=myresolver'
   depends_on:
    - mariadbprod
   restart: always
   environment:
    - 'ASPNETCORE_ENVIRONMENT=Production'
    - 'ConnectionStrings__ApiThetiptop=server=62.210.187.246;port=3308;database=thetiptop_prod;user=root;password=archi20'
   


  front-prod:
   image: dsparchiweb020vm/front_prod
   container_name: front-prod
   networks:
    - web
    - private
   ports:
    - 8088:80
   working_dir: /home/venichelle/front
   labels:
     - 'traefik.enable=true'
     - 'traefik.http.routers.front-prod.rule=Host(`prod.dsp-archiweb020-vm.fr`)'
     - 'traefik.http.routers.front-prod.tls=true'
     - 'traefik.http.routers.front-prod.tls.certresolver=letsencrypt'
     - 'traefik.http.routers.front-prod.service=front-prod'
     - 'traefik.http.services.front-prod.loadbalancer.server.port=80'
     - 'traefik.http.routers.front-prod.entrypoints=websecure'
     - 'traefik.http.routers.front-prod.tls.certresolver=myresolver'
   extra_hosts:
     - "prod.dsp-archiweb020-vm.fr:62.210.187.246"
   depends_on:
    - api-prod
   restart: always
   
   
  
   
  mariadbprod:
   image: mariadb:10.9.3
   #build: $PWD/db/mariadb
   container_name: mariadbprod
   restart: always
   volumes:
    - /home/venichelle/workflow/data/dbprod:/var/lib/mysql
    - ./:/docker-entrypoint-initdb.d
  
   environment:
    MYSQL_DATABASE: thetiptop_prod
    MYSQL_ROOT_PASSWORD: archi20
    MYSQL_USER: root
    MYSQL_PASSWORD: admin
   networks:
    - web
   ports:
    - 3308:3306
    
